# Generated by Django 3.1.3 on 2022-11-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
